#!/usr/bin/env bash
set -euo pipefail

# Generates an .env file populated with Polygon (mainnet) configuration values
# that satisfy the SvelteKit + viem configuration schema.
#
# Usage:
#   ./scripts/env/generate-polygon-mainnet-env.sh
#
# This will write .env.polygon in the project root. Copy or symlink it to .env
# before starting the app:
#   cp .env.polygon .env
#   VITE_DEBUG=true npm run dev

ROOT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/.env.polygon"

cat >"$OUTPUT_FILE" <<'EOF'
# Polygon Mainnet environment configuration
# Generated by scripts/env/generate-polygon-mainnet-env.sh
VITE_CHAIN_ID="137"
PUBLIC_CHAIN_ID="137"

VITE_RPC_URL="https://polygon-rpc.com"
PUBLIC_RPC_URL="https://polygon-rpc.com"

# Treasury/token configuration (USDC on Polygon mainnet)
VITE_TOKEN_ADDR="0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
PUBLIC_TOKEN_ADDR="0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"

# Campaign identifier (32-byte hex string)
VITE_CAMPAIGN="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"
PUBLIC_CAMPAIGN="0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

# Reputation scoring bounds
VITE_FLOOR_SCORE="600000"
VITE_CAP_SCORE="1000000"

# Token payout bounds (wei-style integers)
VITE_MIN_PAYOUT="100000000000000000"
VITE_MAX_PAYOUT="5000000000000000000"

# Airdrop contract addresses (replace with deployed mainnet addresses as needed)
VITE_AIRDROP_ECDSA_ADDR="0xA91cF3b1C5C996Ed3F5b97c5C4B13fE1B8F5cF97"
VITE_AIRDROP_ZK_ADDR="0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
VITE_VERIFIER_ADDR="0x57AA6e7448AD8E0A4D3a75fD4fA16D8a021D7E70"

# Curve used for payout scaling
VITE_CURVE="SQRT"

# Optional backend API endpoint (leave unset to use mock mode)
# VITE_API_BASE="https://api.shadowgraph.example"

# WalletConnect configuration
VITE_WALLETCONNECT_PROJECT_ID="d0db319a634269fea0ae6618eb617169"
PUBLIC_WALLETCONNECT_PROJECT_ID="d0db319a634269fea0ae6618eb617169"

# Enable deploy/debug tooling for controlled environments
VITE_DEBUG="false"
EOF

printf "\nWrote Polygon mainnet environment file to %s\n" "$OUTPUT_FILE"
printf "Copy or symlink it to .env before running the app.\n"
