#!/usr/bin/env bash
set -euo pipefail

# Generates a mock-mode .env file containing the minimum set of
# environment variables required by the SvelteKit client.
#
# Usage:
#   ./scripts/env/generate-mock-env.sh
#
# This will create (or overwrite) .env.mock in the project root. Copy or
# symlink it to .env before running npm commands that require env values.

ROOT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$ROOT_DIR/.env.mock"

cat >"$OUTPUT_FILE" <<'EOF'
# Shadowgraph Airdrop Client mock environment
# Generated by scripts/env/generate-mock-env.sh
VITE_CHAIN_ID="11155111"
PUBLIC_CHAIN_ID="11155111"

VITE_RPC_URL="https://rpc.sepolia.org"
PUBLIC_RPC_URL="https://rpc.sepolia.org"
SEPOLIA_RPC_URLS="https://rpc.sepolia.org,https://ethereum-sepolia.publicnode.com"
MUMBAI_RPC_URLS="https://rpc-mumbai.maticvigil.com,https://polygon-mumbai-bor.publicnode.com"

VITE_TOKEN_ADDR="0x1234567890123456789012345678901234567890"
PUBLIC_TOKEN_ADDR="0x1234567890123456789012345678901234567890"

VITE_CAMPAIGN="0x1234567890123456789012345678901234567890123456789012345678901234"
PUBLIC_CAMPAIGN="0x1234567890123456789012345678901234567890123456789012345678901234"

VITE_FLOOR_SCORE="600000"
VITE_CAP_SCORE="1000000"

VITE_MIN_PAYOUT="100"
VITE_MAX_PAYOUT="1000"

VITE_CURVE="SQRT"

# Leave VITE_API_BASE unset to enable mock mode

VITE_AIRDROP_ECDSA_ADDR="0x1234567890123456789012345678901234567890"
VITE_AIRDROP_ZK_ADDR="0x0000000000000000000000000000000000000000"
VITE_VERIFIER_ADDR="0x0000000000000000000000000000000000000000"

VITE_WALLETCONNECT_PROJECT_ID="test-project-id"
PUBLIC_WALLETCONNECT_PROJECT_ID="test-project-id"

VITE_DEBUG="true"
EOF

printf "\nWrote mock environment file to %s\n" "$OUTPUT_FILE"
printf "Copy or symlink it to .env before running the client.\n"
