/**
 * Circuit Hash Manifest
 * Generated by scripts/generate-mock-circuits.js
 *
 * These SHA-256 hashes are used for integrity verification when downloading circuits.
 * Update this file whenever circuit artifacts are regenerated.
 */

export const CIRCUIT_HASHES: Record<string, string> = {
  "16": "c83b07f9bbddbb8c2f66aafd19e3636e74a228a3cec4d850628194c050e3aa6c",
  "32": "ef952a2a2e31dc681be8849167a11b87fc3feb0ca5a34b54568377990e837d3a",
  "64": "dc25dbbfe507a03e53d4ab039a3d70d30412f3fe963931a34c4c4fcf2cbd9455",
};
